### PR TITLE
Configure eslint and run autofix

### PR DESCRIPTION
**Pull request by JRobsonJr**
This PR adds eslint to the project, so that it becomes easier to improve the source code's readability. It is configured to use [airbnb's rules](https://github.com/airbnb/javascript). 

This also corrects most of the problems by using eslint's autofix feature. Most problems fixed here include:
- Use 4 spaces as tab across the whole code to keep it consistent;
- Add/remove spaces where it was needed to improve readability;
- Encourage the use of single quotes, template strings and arrow functions.

### CODE REVIEW

**Comment by inyee786** [comment]
thanks, @JRobsonJr , 
can you rebase your code

**Comment by bhaskarhc** [comment]
thank u @JRobsonJr

**Comment by JRobsonJr** [comment]
Done, @inyee786!

**Comment by inyee786** [comment]
tried to run your change in my local their was an error 

```
workloads-backend/routes/kubernetes/kubesequence.js:160
                        })).then((podDetails) => {
                          ^

SyntaxError: Unexpected token )
```
@JRobsonJr can you resolve the error

**Pull request closed without merging**
